# -*- C++ -*- LighteningZero

# Copyright (C) 2020  Lightening Zero
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https:#www.gnu.org/licenses/>.

name: CI-format

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-clang-format:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: ${{ github.head_ref }}
    
    - name: install clang-format
      run: |
        sudo apt install clang-format
    
    - name: format files
      run: |
        scripts/format-all-files.sh
    
    - name: commit files
      run: |
        git config --global user.name "LighteningBot"
        git config --global user.email "segmentoj@outlook.com"
        git add .
        git commit -sm "format c++ codes" -a
      continue-on-error: true
    
    - name: Push change back
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
      continue-on-error: true
